name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run comprehensive validation
        run: |
          nix develop .# --command bash -c "
            set -e
            echo '=== Running project validation ==='
            make check-mira
            ./tests/validate.sh
            echo '=== Running tests ==='
            make test
            echo '=== Running additional checks ==='
            make run > /dev/null
            echo '=== All validation checks passed ==='
          "
